"""empty message

Revision ID: 405d37920899
Revises: 0e82eba1cdcf
Create Date: 2024-04-04 00:12:17.964663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405d37920899'
down_revision = '0e82eba1cdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_venues')
    op.drop_table('show_artists')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.create_table('show_artists',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='show_artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='show_artists_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'artist_id', name='show_artists_pkey')
    )
    op.create_table('show_venues',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='show_venues_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='show_venues_venue_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'venue_id', name='show_venues_pkey')
    )
    # ### end Alembic commands ###
